import { UserProfile, SmartBin, RewardItem, LeaderboardEntry, Transaction, NotificationItem } from './types';

export const initialProfile: UserProfile = {
  id: 'STUDENT_21BCE',
  name: 'Alex Rivera',
  studentId: '21BCE1042',
  department: 'CSE',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  ecoPts: 2450,
  totalBottles: 245,
  co2OffsetKg: 9.8,
  rank: 14,
  streakDays: 12,
  weeklyBottles: 7,
  weeklyGoal: 10,
};

export const initialBins: SmartBin[] = [
  {
    id: 'BIN-101',
    name: 'Central Library SmartBin',
    location: 'Central Library Main Entrance',
    capacityPercentage: 42,
    status: 'available',
    bottlesToday: 184,
    coordinates: { x: 35, y: 30 },
    distance: '120m away',
  },
  {
    id: 'BIN-102',
    name: 'Main Canteen Block A',
    location: 'Food Court Plaza',
    capacityPercentage: 88,
    status: 'almost-full',
    bottlesToday: 412,
    coordinates: { x: 55, y: 48 },
    distance: '250m away',
  },
  {
    id: 'BIN-103',
    name: 'Student Activity Center (SAC)',
    location: 'SAC Ground Floor Hall',
    capacityPercentage: 25,
    status: 'available',
    bottlesToday: 129,
    coordinates: { x: 20, y: 65 },
    distance: '380m away',
  },
  {
    id: 'BIN-104',
    name: 'Engineering Block B',
    location: 'CSE & EEE Quadrangle',
    capacityPercentage: 65,
    status: 'available',
    bottlesToday: 290,
    coordinates: { x: 75, y: 35 },
    distance: '190m away',
  },
  {
    id: 'BIN-105',
    name: 'Sports Complex Quad',
    location: 'Near Basketball Courts',
    capacityPercentage: 95,
    status: 'full',
    bottlesToday: 510,
    coordinates: { x: 80, y: 75 },
    distance: '500m away',
  },
  {
    id: 'BIN-106',
    name: 'Hostel Quad 3',
    location: 'Residential Zone Courtyard',
    capacityPercentage: 15,
    status: 'available',
    bottlesToday: 95,
    coordinates: { x: 45, y: 80 },
    distance: '620m away',
  },
];

export const initialRewards: RewardItem[] = [
  {
    id: 'RWD-001',
    title: 'Morning Coffee',
    category: 'canteen',
    pts: 100,
    description: 'Any small hot beverage from the Main Canteen.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&auto=format&fit=crop&q=80',
    vendor: 'Main Campus Canteen',
  },
  {
    id: 'RWD-002',
    title: '10 Page Print',
    category: 'stationery',
    pts: 150,
    description: 'Digital credit for black & white printing at Central Lib.',
    image: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=400&auto=format&fit=crop&q=80',
    vendor: 'Central Library Print Desk',
  },
  {
    id: 'RWD-003',
    title: 'uppETure T-Shirt',
    category: 'merch',
    pts: 450,
    description: 'Limited edition charcoal tee with sustainability logo.',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=400&auto=format&fit=crop&q=80',
    vendor: 'Campus Store',
  },
  {
    id: 'RWD-004',
    title: 'Fest VIP Pass',
    category: 'events',
    pts: 3500,
    description: 'Front row access + backstage tours for upcoming College Fest.',
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&auto=format&fit=crop&q=80',
    vendor: 'Cultural Committee',
  },
  {
    id: 'RWD-005',
    title: 'Organic Fruit Smoothie',
    category: 'canteen',
    pts: 180,
    description: 'Freshly blended berry or mango smoothie at Canteen Juice Bar.',
    image: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=400&auto=format&fit=crop&q=80',
    vendor: 'Green Juice Bar',
  },
  {
    id: 'RWD-006',
    title: 'Recycled Paper Notebook',
    category: 'stationery',
    pts: 220,
    description: 'Eco-friendly grid notebook made from 100% recycled paper.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
    vendor: 'Central Stationery',
  },
];

export const initialLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    name: 'Aaliyah Thorne',
    department: 'Computer Science',
    bottles: 1204,
    ecoPts: 18200,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    badge: 'MASTER RECYCLER',
  },
  {
    rank: 2,
    name: 'Marcus Chen',
    department: 'Mechanical Eng.',
    bottles: 842,
    ecoPts: 12500,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    rank: 3,
    name: 'Jordan Smith',
    department: 'Economics',
    bottles: 719,
    ecoPts: 10800,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    rank: 4,
    name: 'Elena Rodriguez',
    department: 'EEE',
    bottles: 582,
    ecoPts: 8450,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    rank: 5,
    name: 'Liam O\'Connor',
    department: 'CSE',
    bottles: 541,
    ecoPts: 7920,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    rank: 6,
    name: 'Priya Sharma',
    department: 'Biotech',
    bottles: 510,
    ecoPts: 7600,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    rank: 7,
    name: 'David Kim',
    department: 'Civil',
    bottles: 480,
    ecoPts: 6950,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
  },
  {
    rank: 8,
    name: 'Sophia Patel',
    department: 'ECE',
    bottles: 430,
    ecoPts: 6200,
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
  },
  {
    rank: 14,
    name: 'Alex Rivera',
    studentId: '21BCE1042',
    department: 'CSE',
    bottles: 245,
    ecoPts: 2450,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isCurrentUser: true,
  },
];

export const initialTransactions: Transaction[] = [
  {
    id: 'TXN-901',
    type: 'deposit',
    title: 'Recycled 5 PET Bottles at Central Lib Bin',
    amountPts: 50,
    timestamp: 'Today, 10:14 AM',
  },
  {
    id: 'TXN-902',
    type: 'redemption',
    title: 'Redeemed 10 Page Print Credit',
    amountPts: -150,
    timestamp: 'Yesterday, 3:30 PM',
    code: 'PRT-88219-X',
  },
  {
    id: 'TXN-903',
    type: 'deposit',
    title: 'Recycled 8 PET Bottles at SAC Bin',
    amountPts: 80,
    timestamp: '2 days ago',
  },
  {
    id: 'TXN-904',
    type: 'deposit',
    title: 'Streak Bonus (10 Consecutive Days)',
    amountPts: 100,
    timestamp: '3 days ago',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'NOTIF-1',
    title: 'Streak Active!',
    message: 'Your recycling streak reached 12 days. Keep it going!',
    time: '10m ago',
    read: false,
    type: 'streak',
  },
  {
    id: 'NOTIF-2',
    title: 'Campus Rank Up!',
    message: 'You jumped to #14 in CSE department rankings.',
    time: '2h ago',
    read: false,
    type: 'rank',
  },
  {
    id: 'NOTIF-3',
    title: 'Bin Empty Alert',
    message: 'Central Library SmartBin was emptied and ready for deposits.',
    time: '1d ago',
    read: true,
    type: 'bin',
  },
];
